spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 10
        max-wait: 1ms
        min-idle: 5
      shutdown-timeout: 100ms



